name: Build ESPHome Firmware

on:
  push:
    paths:
      - '**.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Compile YAML to BIN
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install ESPHome
        run: |
          python -m pip install --upgrade pip
          pip install esphome

      - name: Compile firmware
        run: |
          esphome compile led-switch.yaml

      - name: Upload firmware binary
        uses: actions/upload-artifact@v3
        with:
          name: led-switch-firmware
          path: .esphome/build/led-switch/firmware.bin
